name: xfraud_test
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pyarrow=0.15.1
  - python=3.7.5
  - pip:
    - dill==0.3.0
    - fire==0.3.1
    - gensim==3.8.2
    - networkx==2.4
    - pandas==0.24.2
    - plyvel==1.3.0
    - py4j==0.10.7
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.9.0
    - tqdm==4.56.0
